CREATE TABLE IF NOT EXISTS Statuses (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS CardStatuses (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS Priorities (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS Difficulties (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS Tags (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS Projects (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS Sections (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	ProjectId INTEGER REFERENCES Projects (Id) ON DELETE SET NULL ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS Tasks (
	Id INTEGER PRIMARY KEY,
	Header TEXT NOT NULL,
	Description TEXT,
	Deadline TEXT,
	Progress INTEGER DEFAULT 0,
	CreatedAt TEXT NOT NULL,
	UpdatedAt TEXT NOT NULL,
	StatusId INTEGER NOT NULL REFERENCES Statuses (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CardStatusId INTEGER NOT NULL REFERENCES CardStatuses (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PriorityId INTEGER NOT NULL REFERENCES Priorities (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	DifficultyId INTEGER NOT NULL REFERENCES Difficulties (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	SectionId INTEGER REFERENCES Sections (Id) ON DELETE SET NULL ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS Subtasks (
	Id INTEGER PRIMARY KEY,
	Text TEXT NOT NULL,
	IsCompleted INTEGER DEFAULT 0,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS AttachedLinks (
	Id INTEGER PRIMARY KEY,
	Text TEXT NOT NULL,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS Comments (
	Id INTEGER PRIMARY KEY,
	Text TEXT NOT NULL,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS TagReferences (
	Id INTEGER PRIMARY KEY,
	TagId INTEGER NOT NULL REFERENCES Tags (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	TaskId INTEGER NOT NULL REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

