DROP DATABASE eDiary

CREATE DATABASE eDiary

USE eDiary

CREATE TABLE Statuses (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL
)

CREATE TABLE CardStatuses (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL
)

CREATE TABLE Priorities (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL
)

CREATE TABLE Difficulties (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL
)

CREATE TABLE Tags (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE UserProfiles (
	Id INTEGER PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50),
	Email NVARCHAR(320) NOT NULL
)

CREATE TABLE ProjectCategories (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	UserId INTEGER NOT NULL REFERENCES UserProfiles (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Projects (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	CategoryId INTEGER REFERENCES ProjectCategories (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	UserId INTEGER NOT NULL REFERENCES UserProfiles (Id) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE Sections (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	ProjectId INTEGER NOT NULL REFERENCES Projects (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Tasks (
	Id INTEGER PRIMARY KEY IDENTITY,
	Header NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX),
	Deadline DATETIME,
	Progress INTEGER DEFAULT 0,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	StatusId INTEGER NOT NULL REFERENCES Statuses (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	CardStatusId INTEGER NOT NULL REFERENCES CardStatuses (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	PriorityId INTEGER NOT NULL REFERENCES Priorities (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	DifficultyId INTEGER NOT NULL REFERENCES Difficulties (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	SectionId INTEGER REFERENCES Sections (Id) ON DELETE SET NULL ON UPDATE CASCADE
)

CREATE TABLE Subtasks (
	Id INTEGER PRIMARY KEY IDENTITY,
	Text NVARCHAR(MAX) NOT NULL,
	IsCompleted INTEGER DEFAULT 0 NOT NULL,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Comments (
	Id INTEGER PRIMARY KEY IDENTITY,
	TaskId INTEGER NOT NULL REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	Text NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME NOT NULL
)

CREATE TABLE Folders (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	ParentFolderId INTEGER REFERENCES Folders (Id) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE Notes (
	Id INTEGER PRIMARY KEY IDENTITY,
	Header NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX),
	StatusId INTEGER NOT NULL REFERENCES Statuses (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	FolderId INTEGER NOT NULL REFERENCES Folders (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL
) 

CREATE TABLE AttachedLinks (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(MAX),
	Link NVARCHAR(MAX) NOT NULL,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	NoteId INTEGER REFERENCES Notes (Id) ON DELETE CASCADE ON UPDATE NO ACTION
)

CREATE TABLE TagReferences (
	Id INTEGER PRIMARY KEY IDENTITY,
	TagId INTEGER NOT NULL REFERENCES Tags (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	NoteId INTEGER REFERENCES Notes (Id) ON DELETE CASCADE ON UPDATE NO ACTION
)

CREATE TABLE AttachedFiles (
	Id INTEGER PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Link NVARCHAR(MAX) NOT NULL,
	TaskId INTEGER REFERENCES Tasks (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	NoteId INTEGER REFERENCES Notes (Id) ON DELETE CASCADE ON UPDATE NO ACTION
)

CREATE TABLE AppUsers (
	Id INTEGER PRIMARY KEY IDENTITY,
	UserProfileId INTEGER NOT NULL REFERENCES UserProfiles (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	Username NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Languages(
	Id INTEGER PRIMARY KEY IDENTITY,
	ShortCode NVARCHAR(2) NOT NULL
)

CREATE TABLE UserSettings (
	Id INTEGER PRIMARY KEY IDENTITY,
	UserId INTEGER NOT NULL REFERENCES UserProfiles (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	LanguageId INTEGER REFERENCES Languages (Id) ON DELETE SET NULL ON UPDATE CASCADE,
	RootFolderId INTEGER NOT NULL REFERENCES Folders (Id) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE Sessions (
	Id INTEGER PRIMARY KEY IDENTITY,
	AppUserId INTEGER NOT NULL REFERENCES AppUsers (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	Token NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME NOT NULL
)